In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 6 4]
(array([3, 6]),)


In [5]:
#indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [7]:
#sorting the array
arr=np.array([3,2,0,1])
print("\n original array:",arr)
print("\n sorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\n original array:",arr)
print("\n sorted array",np.sort(arr))


 original array: [3 2 0 1]

 sorted array: [0 1 2 3]

 original array: [[3 2 4]
 [5 0 1]]

 sorted array [[2 3 4]
 [0 1 5]]


In [12]:
import numpy as np
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)




















































































[1 3 5 7]
[2, 4, 6]
[1 2 3]


In [16]:
#fliter
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [19]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]
