In [11]:
import numpy as np

# Generate random stock price matrices (5 days × 3 features)
stockA = np.random.randint(90, 120, (5,3))
stockB = np.random.randint(90, 120, (5,3))

print("Stock A Data:\n", stockA)
print("\nStock B Data:\n", stockB)

# Element-wise sum
sum_matrix = stockA + stockB

# Element-wise difference
diff_matrix = stockA - stockB

print("\nElement-wise Sum:\n", sum_matrix)
print("\nElement-wise Difference:\n", diff_matrix)

Stock A Data:
 [[117 110 115]
 [102 100 108]
 [ 94  99 102]
 [ 93  99 106]
 [ 91 114 116]]

Stock B Data:
 [[ 91 103  94]
 [ 95 108 114]
 [109 118  99]
 [ 99 113  96]
 [ 95  99 107]]

Element-wise Sum:
 [[208 213 209]
 [197 208 222]
 [203 217 201]
 [192 212 202]
 [186 213 223]]

Element-wise Difference:
 [[ 26   7  21]
 [  7  -8  -6]
 [-15 -19   3]
 [ -6 -14  10]
 [ -4  15   9]]
