In [6]:
import numpy as np

grades = np.random.randint(50, 100, size=(30,3))   # 30 students, 3 subjects, grades between 50 and 100

print("Grades Matrix:\n", grades)

print("Subject Average:", grades.mean(axis=0))
print("Highest Marks:", grades.max())
print("Lowest Marks:", grades.min())

total = grades.sum(axis=1)
top_student = total.argmax()

print("Top Student Index:", top_student)

Grades Matrix:
 [[67 83 60]
 [64 88 64]
 [99 75 60]
 [77 62 82]
 [66 62 76]
 [69 85 70]
 [84 60 87]
 [63 75 97]
 [51 57 92]
 [98 62 97]
 [73 68 93]
 [56 89 93]
 [53 65 96]
 [74 80 82]
 [86 90 84]
 [57 97 57]
 [86 59 70]
 [73 88 87]
 [51 79 87]
 [52 81 68]
 [72 60 51]
 [53 59 92]
 [67 96 89]
 [99 70 82]
 [78 94 57]
 [82 58 90]
 [59 52 74]
 [99 81 78]
 [92 51 57]
 [61 58 69]]
Subject Average: [72.03333333 72.8        78.03333333]
Highest Marks: 99
Lowest Marks: 51
Top Student Index: 14
